In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
test = pd.read_csv('test_clean.csv')
train = pd.read_csv('train_clean.csv')

In [3]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             367 non-null    int64  
 1   Married            367 non-null    int64  
 2   Dependents         367 non-null    int64  
 3   Education          367 non-null    int64  
 4   Self_Employed      367 non-null    int64  
 5   ApplicantIncome    367 non-null    int64  
 6   CoapplicantIncome  367 non-null    float64
 7   LoanAmount         367 non-null    float64
 8   Loan_Amount_Term   367 non-null    float64
 9   Credit_History     367 non-null    int64  
 10  Property_Area      367 non-null    int64  
 11  Total_Income       367 non-null    float64
dtypes: float64(4), int64(8)
memory usage: 34.5 KB


In [4]:
train.shape

(614, 13)

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             614 non-null    int64  
 1   Married            614 non-null    int64  
 2   Dependents         614 non-null    int64  
 3   Education          614 non-null    int64  
 4   Self_Employed      614 non-null    int64  
 5   ApplicantIncome    614 non-null    int64  
 6   CoapplicantIncome  614 non-null    float64
 7   LoanAmount         614 non-null    float64
 8   Loan_Amount_Term   614 non-null    float64
 9   Credit_History     614 non-null    int64  
 10  Property_Area      614 non-null    int64  
 11  Loan_Status        614 non-null    int64  
 12  Total_Income       614 non-null    float64
dtypes: float64(4), int64(9)
memory usage: 62.5 KB


In [6]:
test

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        1           0          0              0             5720   
1         1        1           1          0              0             3076   
2         1        1           2          0              0             5000   
3         1        1           2          0              0             2340   
4         1        0           0          1              0             3276   
..      ...      ...         ...        ...            ...              ...   
362       1        1           3          1              1             4009   
363       1        1           0          0              0             4158   
364       1        0           0          0              0             3250   
365       1        1           0          0              0             5000   
366       1        0           0          0              1             9200   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0       110.0             360.0               1   
1               1500.0       126.0             360.0               1   
2               1800.0       208.0             360.0               1   
3               2546.0       100.0             360.0               1   
4                  0.0        78.0             360.0               1   
..                 ...         ...               ...             ...   
362             1777.0       113.0             360.0               1   
363              709.0       115.0             360.0               1   
364             1993.0       126.0             360.0               1   
365             2393.0       158.0             360.0               1   
366                0.0        98.0             180.0               1   

     Property_Area  Total_Income  
0                2        5720.0  
1                2        4576.0  
2                2        6800.0  
3                2        4886.0  
4                2        3276.0  
..             ...           ...  
362              2        5786.0  
363              2        4867.0  
364              1        5243.0  
365              0        7393.0  
366              0        9200.0  

[367 rows x 12 columns]

In [7]:
train

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0         1        0           0          0              0             5849   
1         1        1           1          0              0             4583   
2         1        1           0          0              1             3000   
3         1        1           0          1              0             2583   
4         1        0           0          0              0             6000   
..      ...      ...         ...        ...            ...              ...   
609       0        0           0          0              0             2900   
610       1        1           3          0              0             4106   
611       1        1           1          0              0             8072   
612       1        1           2          0              0             7583   
613       0        0           0          0              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0  146.412162             360.0               1   
1               1508.0  128.000000             360.0               1   
2                  0.0   66.000000             360.0               1   
3               2358.0  120.000000             360.0               1   
4                  0.0  141.000000             360.0               1   
..                 ...         ...               ...             ...   
609                0.0   71.000000             360.0               1   
610                0.0   40.000000             180.0               1   
611              240.0  253.000000             360.0               1   
612                0.0  187.000000             360.0               1   
613                0.0  133.000000             360.0               0   

     Property_Area  Loan_Status  Total_Income  
0                2            1        5849.0  
1                0            0        6091.0  
2                2            1        3000.0  
3                2            1        4941.0  
4                2            1        6000.0  
..             ...          ...           ...  
609              0            1        2900.0  
610              0            1        4106.0  
611              2            1        8312.0  
612              2            1        7583.0  
613              1            0        4583.0  

[614 rows x 13 columns]

In [8]:
#train.iloc[:, [11]]


In [9]:
#train.drop('Loan_Status', axis = 1)
#train.drop(train.iloc[:, [11]], axis = 1)


In [10]:
x = train.drop(train.iloc[:, [7]], axis = 1)
y = train.iloc[:, [7]]

#splitting the test and treain
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [11]:
#feature scaling using standard scaler

from sklearn.preprocessing import StandardScaler 

sc = StandardScaler()
x_train = sc.fit_transform(x_train) 
x_test = sc.fit_transform(x_test)

In [12]:
x_train.shape

(460, 12)

In [13]:
y_train.shape

(460, 1)

In [14]:
x.shape

(614, 12)

In [15]:
y.shape

(614, 1)

In [16]:
test.shape

(367, 12)

### Logistic Regression

In [20]:
lr = LogisticRegression(random_state = 43, C = 0.7)
lr.fit(x_train, y_train.values.ravel())

ValueError: Unknown label type: 'continuous'

In [ ]:
#prediciting the test result

ypred_lr = lr.predict(x_test)

In [19]:
print(classification_report(y_test, ypred_lr))

              precision    recall  f1-score   support

           0       0.91      0.47      0.62        43
           1       0.83      0.98      0.90       111

    accuracy                           0.84       154
   macro avg       0.87      0.72      0.76       154
weighted avg       0.85      0.84      0.82       154



In [20]:
lr.predict(test)

array([1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,

### Naive Bayes Classifier

In [21]:
classifier_nb = GaussianNB()
classifier_nb.fit(x_train, y_train.values.ravel())

GaussianNB()

In [22]:
ypred_nb = classifier_nb.predict(x_test)

In [23]:
print(classification_report(y_test, ypred_nb))

              precision    recall  f1-score   support

           0       0.83      0.47      0.60        43
           1       0.82      0.96      0.89       111

    accuracy                           0.82       154
   macro avg       0.83      0.71      0.74       154
weighted avg       0.83      0.82      0.81       154



In [24]:
classifier_nb.predict(test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

### Decision Tree

In [25]:
classifier_dc = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier_dc.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [26]:
ypred_dc = classifier_dc.predict(x_test)

In [27]:
print(classification_report(y_test, ypred_dc))

              precision    recall  f1-score   support

           0       0.48      0.67      0.56        43
           1       0.85      0.71      0.77       111

    accuracy                           0.70       154
   macro avg       0.66      0.69      0.67       154
weighted avg       0.75      0.70      0.71       154



In [28]:
classifier_dc.predict(test)

array([1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,

### Random Forest Classifier

In [29]:
classifier_rf = RandomForestClassifier()

parameters ={"n_estimators": [50, 100, 150, 200, 250, 500, 700],
            "max_depth": [2, 4, 6, 8, 10, None]}

cv = GridSearchCV(classifier_rf, parameters, )

cv.fit(x_train, y_train.values.ravel())

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'max_depth': [2, 4, 6, 8, 10, None],
                         'n_estimators': [50, 100, 150, 200, 250, 500, 700]})

In [30]:
def display(results):
    print(f'Best parameters are: {results.best_params_}')
    print('\n')
    mean_score = results.cv_results_['mean_test_score']
    std_score = results.cv_results_['std_test_score']
    params = results.cv_results_['params']
    for mean,std,params in zip(mean_score, std_score, params):
        print(f'{round(mean, 3)} + or -{round(std, 3)} for the {params}')

In [31]:
display(cv)

Best parameters are: {'max_depth': 6, 'n_estimators': 50}


0.798 + or -0.032 for the {'max_depth': 2, 'n_estimators': 50}
0.796 + or -0.031 for the {'max_depth': 2, 'n_estimators': 100}
0.802 + or -0.029 for the {'max_depth': 2, 'n_estimators': 150}
0.802 + or -0.029 for the {'max_depth': 2, 'n_estimators': 200}
0.802 + or -0.029 for the {'max_depth': 2, 'n_estimators': 250}
0.802 + or -0.029 for the {'max_depth': 2, 'n_estimators': 500}
0.802 + or -0.029 for the {'max_depth': 2, 'n_estimators': 700}
0.798 + or -0.024 for the {'max_depth': 4, 'n_estimators': 50}
0.807 + or -0.03 for the {'max_depth': 4, 'n_estimators': 100}
0.802 + or -0.027 for the {'max_depth': 4, 'n_estimators': 150}
0.802 + or -0.027 for the {'max_depth': 4, 'n_estimators': 200}
0.8 + or -0.026 for the {'max_depth': 4, 'n_estimators': 250}
0.802 + or -0.027 for the {'max_depth': 4, 'n_estimators': 500}
0.802 + or -0.028 for the {'max_depth': 4, 'n_estimators': 700}
0.811 + or -0.033 for the {'max_depth': 6, 'n_est

In [44]:
rfc = RandomForestClassifier(n_estimators = 50, max_depth = 6)
rfc.fit(x_train, y_train.values.ravel())

RandomForestClassifier(max_depth=6, n_estimators=50)

In [45]:
ypred_rf = rfc.predict(x_test)

In [46]:
print(classification_report(y_test, ypred_rf))

              precision    recall  f1-score   support

           0       0.62      0.53      0.57        43
           1       0.83      0.87      0.85       111

    accuracy                           0.78       154
   macro avg       0.73      0.70      0.71       154
weighted avg       0.77      0.78      0.77       154



In [47]:
rfc.predict(test)

array([1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,